files:
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: docs/contributing/**/*.md
    translation: /docs/%two_letters_code%/contributing/%original_file_name%
  - source: /docs/diagnostics/*.md
    translation: /docs/%two_letters_code%/diagnostics/%original_file_name%
    ignore:
      - /docs/diagnostics/index.md
  - source: /docs/features/**/*.md
    translation: /docs/%two_letters_code%/features/%original_file_name%
  - source: /docs/reporters/**/*.md
    translation: /docs/%two_letters_code%/reporters/%original_file_name%
