name: Benchmark

on:
  push: 
    branches:
      - develop
      - master
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew jar

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Setup pytest-benchmark
        run: pip install pytest pytest-benchmark

      - name: Download SSL 3.1
        run: git clone https://github.com/1c-syntax/ssl_3_1.git ssl

      - name: Analyze ssl
        run: pytest .github/scripts/bechmark.py --benchmark-min-rounds=1 --benchmark-timer=time.time --benchmark-json=output.json --benchmark-verbose

      - name: Check benchmark result for pull request
        if: github.event_name == 'pull_request'
        uses: otymko/github-action-benchmark@v1
        with:
          name: BSL LS perfomance measurement (SSL 3.1)
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '10%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@otymko'

      - name: Store benchmark result into branch
        if: github.event_name == 'push'
        uses: otymko/github-action-benchmark@v1
        with:
          name: BSL LS perfomance measurement (SSL 3.1)
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '10%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@otymko'
