name: Publish to m2

on: [push]

jobs:
  gpr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.event.repository.full_name
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Github Package Registry publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_DEPLOY_KEY: ${{ secrets.GPR_DEPLOY_KEY }}
          GPR_USER: ${{ github.actor }}
