name: Publish to m2

on:
  push:
  release:
      types: [published]

jobs:
  gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Github Package Registry publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_DEPLOY_KEY: ${{ secrets.GPR_DEPLOY_KEY }}
          GPR_USER: ${{ github.actor }}
